# Generated by Django 3.2 on 2023-08-09 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment', models.CharField(max_length=50)),
                ('is_takeout', models.BooleanField(default=True)),
                ('total_price', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=50)),
                ('product_detail', models.CharField(blank=True, default='', max_length=50)),
                ('price', models.IntegerField(default=0)),
                ('is_soldout', models.BooleanField(default=False)),
                ('quantity', models.IntegerField(default=0)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product', to='NewKiosk.category')),
            ],
        ),
        migrations.CreateModel(
            name='Receipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='receipt', to='NewKiosk.order')),
                ('product', models.ManyToManyField(related_name='receipt', to='NewKiosk.Product')),
            ],
        ),
        migrations.CreateModel(
            name='Product_Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_order', to='NewKiosk.order')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='product_order', to='NewKiosk.product')),
            ],
        ),
        migrations.AddField(
            model_name='product',
            name='related_order',
            field=models.ManyToManyField(related_name='a_product', through='NewKiosk.Product_Order', to='NewKiosk.Order'),
        ),
        migrations.AddField(
            model_name='order',
            name='products',
            field=models.ManyToManyField(related_name='ordered', through='NewKiosk.Product_Order', to='NewKiosk.Product'),
        ),
    ]
