# Generated by Django 4.2.3 on 2023-07-31 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewKiosk', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_detail',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
