# Generated by Django 4.2.1 on 2023-08-01 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('NewKiosk', '0002_alter_product_product_detail'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='product_detail',
            field=models.CharField(blank=True, default='', max_length=50),
        ),
    ]
