# Generated by Django 3.2 on 2023-08-03 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('NewKiosk', '0003_alter_product_product_detail'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product_order',
            old_name='order_num',
            new_name='quantity',
        ),
        migrations.RemoveField(
            model_name='product_order',
            name='price',
        ),
    ]
